INSERT INTO Note (id, title, content) VALUES
    (1, 'Note 1', 'Content for Note 1'),
    (2, 'Note 2', 'Content for Note 2'),
    (3, 'Note 3', 'Content for Note 3'),
    (4, 'Note 4', 'Content for Note 4'),
    (5, 'Note 5', 'Content for Note 5'),
    (6, 'Note 6', 'Content for Note 6'),
    (7, 'Note 7', 'Content for Note 7'),
    (8, 'Note 8', 'Content for Note 8'),
    (9, 'Note 9', 'Content for Note 9'),
    (10, 'Note 10', 'Content for Note 10');